travis:
  secure:
    BINSTAR_TOKEN: nReRw+2/fETQb8kWEBHNkK+ILKv+yZsl7XYV4wuHrKNuZ2jpGJkcNrSfrAXja9OuizeMJLmQR8bDKyVcU9Ll0f/L5QNxvLVZVX6Ax1eLTaPlFIUwLK3Gpeou6hoaGtDerijPsIGkOuF41iwvA3yqbMMCF8oZmKRHLL+I1xzK9TdyZX/BXYG9kzl36mb3ysuAHskhv66fwpRnovuL3SRYs3NlAl8u26O+qP2f6V/CKYa6zhtCndvnL4H87gEtam/HSuevXMwRzBBthxbAx3XIQB1bL4ycvKQeqlUsvSbLCpnM+GRdKTlmmB3NcQ4xM+GtDoSCEpS404Fr23al95BdHvKF9A4kXpXKrmTECCavv5wV/JIHWTE9SoGdW93ux+POF+9nwW+tm087+jBNwZYkbFyakiWqurxykK76tyXpqLcRquEHpa0RuLoEWfbEY2pWVFOHfZ7k29bH7rR3kxDmFHsn2gg/ha2tsk/jKFt1HFJqqqaAOIH/jJMM+l6rOsFjmy5jNC4iV83xDx67Vtx3j929UtHy0rmWDr2d9JiOr8xfhnmK2i7+oTcTKBfe+zrex+ds0KcT2x12RoJoCD6LURTPGZ6j9HZ3kiDGPG7jWnBOx/IDGXX6FpmdsGD/EH+GHwiZoTpeda53LBoAg3Gol2D0l5LMiRMEeBLYgJJcI/8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
